// <auto-generated />
namespace CmsShoppingCart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _290911 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_290911));
        
        string IMigrationMetadata.Id
        {
            get { return "201709291728338_29-09-11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
