// <auto-generated />
namespace CmsShoppingCart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _290917Two : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_290917Two));
        
        string IMigrationMetadata.Id
        {
            get { return "201709292002310_29-09-17Two"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
